services:
  postgres:
    image: postgres:latest
    container_name: database-lab-postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - ./scripts:/scripts
      - ./scripts/0-create-database.sql:/docker-entrypoint-initdb.d/init.sql
 